### ISSUE TITLE
Only First Filter is Used

### ISSUE THREAD

**Issue by Zipties** [MangoScango/autodl-chatzilla#1]
I am not sure if this project is still maintained, but I have discovered a bug where it seems only the first filter setup is being used. To get around it I have had to actually create multiple windows profiles, and to run chatzilla as a different user for each filter.

**Comment by MangoScango** [comment]
Interesting. I can't say that I've encountered that. But, this is something
I still use, so when I get some time, I'll take a look and see if I can't
fix that.

You're saying only the first filter period? Or say like, the first filter
per tracker?

**Comment by Zipties** [comment]
> Interesting. I can't say that I've encountered that. But, this is something I still use, so when I get some time, I'll take a look and see if I can't fix that. You're saying only the first filter period? Or say like, the first filter per tracker?
> .

Hey, thank you for the quick reply. It seems to be the first filter period. I had setup two filters, one to send torrents to Sonarr, and another to send them to Radarr. Only the first one on the list would ever report to the *client* tab.

**Comment by Zipties** [comment]
So, I have been playing with it some more and I am a little more confused. 

![image](https://user-images.githubusercontent.com/11506166/74465797-aa0a1780-4e5b-11ea-8885-de2f3d3105b2.png)

EverythingSonarr & EverythignRadarr are set up identically, except one reports to sonarr, and the other radarr. But, only Sonarr reports in the client tab as shown. Confusingly,  the MaM filter does work though. 

![image](https://user-images.githubusercontent.com/11506166/74465991-00775600-4e5c-11ea-92d7-0101b7826cdc.png)

**Comment by MangoScango** [comment]
I'll have to look into it a little further, because this is really just a project I hacked on to and don't know much about how it was designed, but I think this plugin is only meant to match one filter per release. If you're trying to announce every torrent to Sonarr AND radarr, I think we would need to implement a separate action for that.

Here's how my filters are set up:

![image](https://user-images.githubusercontent.com/7623678/74466987-46d1b280-4e66-11ea-9639-51e90f916d21.png)
![image](https://user-images.githubusercontent.com/7623678/74467086-6d8fe900-4e66-11ea-8479-d366747b8add.png)
which announces to sonarr

![image](https://user-images.githubusercontent.com/7623678/74467107-754f8d80-4e66-11ea-94ee-54a616ad9b37.png)
![image](https://user-images.githubusercontent.com/7623678/74467118-7b456e80-4e66-11ea-85c0-538877a83786.png)
![image](https://user-images.githubusercontent.com/7623678/74467136-84ced680-4e66-11ea-8908-82bf664a1fd3.png)
![image](https://user-images.githubusercontent.com/7623678/74467158-8d271180-4e66-11ea-9c1c-17ddbe571d81.png)
![image](https://user-images.githubusercontent.com/7623678/74467168-90ba9880-4e66-11ea-8248-f2ff5abdb7df.png)
All announce to radarr

So no torrent would ever be announced to both sonarr and radarr. If you really want to set it up that way so they are always announced to both, I may be able to create a new action to do that, but it will take me some time as it's been awhile since I've worked on this,

**Comment by Zipties** [comment]
Ah, that makes sense. So I just need to set up separate filters for each tracker that has differently named categories, and seperate the movies from the TV filters. It appears to be working now for me. 

I really appreciate the help. I am also really thankful for you updating this for Sonarr and Radarr. It has been a big boost to my workflow.
